### ISSUE TITLE
Backup Memory

### ISSUE THREAD

**Issue by WGR7** [ijacquez/libyaul#69]
Hi

I didn't see support for backup memory access. Do you plan to do it?

Regards

**Comment by ijacquez** [comment]
I don't have anything on my roadmap for adding support myself, but certainly, it's much needed.

I believe that the BUP functionality can be easily implemented because they're simply BIOS calls.

If you look [here](https://github.com/ijacquez/libyaul/blob/develop/libyaul/scu/scu/ic.h#L86-L93), this is the overall structure of a BIOS call.

I certainly would accept a PR with the changes. I believe you can find out what the BIOS call addresses are [here](https://ppcenter.webou.net/pskai/#download).

**Comment by ijacquez** [comment]
Seeing as there isn't much of a conversation, I'll add this to my road map.

Closing.
